### ISSUE TITLE
Erro in Using it

### ISSUE THREAD

**Issue by jmandivarapu1** [mjsolidarios/react-native-search-filter#6]
I want to use this filter functionality.
But when i tried to install this in my app and use it i am getting the error.
But when i uninstall everything is running fine back to normal.

Can you plz help me with this weather i am wrong or right in my thinking

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at Object.readSync (/Users/Jay/Downloads/templates/react-native-shop-ui-master/node_modules/graceful-fs/polyfills.js:138:28)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at Module._readSourceCode (/Users/Jay/Downloads/templates/react-native-shop-ui-master/node_modules/metro-bundler/build/node-haste/Module.js:205:29)
    at Module._getCacheProps (/Users/Jay/Downloads/templates/react-native-shop-ui-master/node_modules/metro-bundler/build/node-haste/Module.js:395:29)
    at Module._readFromTransformCache (/Users/Jay/Downloads/templates/react-native-shop-ui-master/node_modules/metro-bundler/build/node-haste/Module.js:345:29)
    at Module.readCached (/Users/Jay/Downloads/templates/react-native-shop-ui-master/node_modules/metro-bundler/build/node-haste/Module.js:332:19)
    at ResolutionRequest.preprocessModule (/Users/Jay/Downloads/templates/react-native-shop-ui-master/node_modules/metro-bundler/build/node-haste/DependencyGraph/ResolutionRequest.js:380:27)

**Comment by mjsolidarios** [comment]
Sorry for the late response @jmandivarapu1. Have you tried deleting your ```node_modules``` and reinstalling your packages again or perhaps resetting your ```npm``` configurations? This [solution](https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a) might help you out.

**Comment by jmandivarapu1** [comment]
<img width="598" alt="screenshot 2017-12-27 15 12 01" src="https://user-images.githubusercontent.com/21245519/34392141-56f06bf6-eb18-11e7-8dd8-da97eb48e6ec.png">


I did followed the above solution with no luck still its giving the same error in the terminal.

**Comment by mjsolidarios** [comment]
Are you using this repository [react-native-search-filter](https://github.com/ATF19/react-native-shop-ui)? I'll try to replicate the problem by adding only my package ```react-native-search-filter``` to confirm this issue.

**Comment by jmandivarapu1** [comment]
Yeah you can try that.

my github repo is https://github.com/jmandivarapu1/City_Wits(you can try in this)

**Comment by JayKurniawan** [comment]
any update for this @mjsolidarios ? 
I also facing this issue

**Comment by mjsolidarios** [comment]
Hello @JayKurniawan. I did a dependency upgrade and cleanup on the *dev* branch can you check the *example-expo* and test it? Let me know if the error still persists. Thanks!

**Comment by mjsolidarios** [comment]
Closed for inactivity
